import Engine from '../Engine';
import EnginePage from '../EnginePage';

import Page from '../../superstatic/Page';
import FileSystem from '../FileSystem';

(function () {
  class Render extends Page {
    constructor({ name, title, description }) {
      super({ name: name, title: title, description: description });
    }

    render() {
      return `
      <main class="main-content">
        <span>${this.props.name}</span>
        <h1>${this.props.title}</h1>
        <p>${this.props.description}</p>
      </main>
      `;
    }
  }
  const props = {
    headless: true
  }

  const engine = new Engine({ props: props });

  async function initEngine() {
    await engine.init();
    await work();
  }

  async function work() {
    console.log('doing some work...')
    const r = new Render({ name: 'render',  title: 'Render Test Page', description: 'A render test page generated by Superstatic' });
    const enginePage = new EnginePage({ engine: engine.instance, page: r });
    let render = await enginePage.construct();

    console.log(render);
    await engine.destroy();

    const fs = new FileSystem({});
    fs.rootFolder = 'dist';
    fs.write({ file: 'index.html', content: render });
  }

  initEngine();
})();